/**
 * CrudSQL API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taqi@mobix.biz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Error response containing an error message
 * @export
 * @interface ApiErrorResponse
 */
export interface ApiErrorResponse {
    /**
     * @Description A descriptive error message
     * @type {string}
     * @memberof ApiErrorResponse
     */
    message?: string;
}
/**
 * Check if a given object implements the ApiErrorResponse interface.
 */
export declare function instanceOfApiErrorResponse(value: object): value is ApiErrorResponse;
export declare function ApiErrorResponseFromJSON(json: any): ApiErrorResponse;
export declare function ApiErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiErrorResponse;
export declare function ApiErrorResponseToJSON(json: any): ApiErrorResponse;
export declare function ApiErrorResponseToJSONTyped(value?: ApiErrorResponse | null, ignoreDiscriminator?: boolean): any;
