/**
 * CrudSQL API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taqi@mobix.biz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ApiRelationshipSchema } from './ApiRelationshipSchema';
import type { ApiFieldSchema } from './ApiFieldSchema';
/**
 * Schema information for a model including fields and relationships
 * @export
 * @interface ApiModelSchema
 */
export interface ApiModelSchema {
    /**
     * Fields contains information about each field in the model
     * @type {Array<ApiFieldSchema>}
     * @memberof ApiModelSchema
     */
    fields?: Array<ApiFieldSchema>;
    /**
     * Relationships contains information about model relationships
     * @type {Array<ApiRelationshipSchema>}
     * @memberof ApiModelSchema
     */
    relationships?: Array<ApiRelationshipSchema>;
}
/**
 * Check if a given object implements the ApiModelSchema interface.
 */
export declare function instanceOfApiModelSchema(value: object): value is ApiModelSchema;
export declare function ApiModelSchemaFromJSON(json: any): ApiModelSchema;
export declare function ApiModelSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiModelSchema;
export declare function ApiModelSchemaToJSON(json: any): ApiModelSchema;
export declare function ApiModelSchemaToJSONTyped(value?: ApiModelSchema | null, ignoreDiscriminator?: boolean): any;
