"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CrudSQL API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taqi@mobix.biz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiRelationshipSchemaToJSONTyped = exports.ApiRelationshipSchemaToJSON = exports.ApiRelationshipSchemaFromJSONTyped = exports.ApiRelationshipSchemaFromJSON = exports.instanceOfApiRelationshipSchema = void 0;
/**
 * Check if a given object implements the ApiRelationshipSchema interface.
 */
function instanceOfApiRelationshipSchema(value) {
    return true;
}
exports.instanceOfApiRelationshipSchema = instanceOfApiRelationshipSchema;
function ApiRelationshipSchemaFromJSON(json) {
    return ApiRelationshipSchemaFromJSONTyped(json, false);
}
exports.ApiRelationshipSchemaFromJSON = ApiRelationshipSchemaFromJSON;
function ApiRelationshipSchemaFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'] == null ? undefined : json['name'],
        'relatedModel': json['relatedModel'] == null ? undefined : json['relatedModel'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}
exports.ApiRelationshipSchemaFromJSONTyped = ApiRelationshipSchemaFromJSONTyped;
function ApiRelationshipSchemaToJSON(json) {
    return ApiRelationshipSchemaToJSONTyped(json, false);
}
exports.ApiRelationshipSchemaToJSON = ApiRelationshipSchemaToJSON;
function ApiRelationshipSchemaToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'relatedModel': value['relatedModel'],
        'type': value['type'],
    };
}
exports.ApiRelationshipSchemaToJSONTyped = ApiRelationshipSchemaToJSONTyped;
