/**
 * CrudSQL API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taqi@mobix.biz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Schema information for a model relationship
 * @export
 * @interface ApiRelationshipSchema
 */
export interface ApiRelationshipSchema {
    /**
     * Name of the relationship
     * @type {string}
     * @memberof ApiRelationshipSchema
     */
    name?: string;
    /**
     * Name of the related model
     * @type {string}
     * @memberof ApiRelationshipSchema
     */
    relatedModel?: string;
    /**
     * Type of relationship (hasOne, hasMany)
     * @type {string}
     * @memberof ApiRelationshipSchema
     */
    type?: string;
}
/**
 * Check if a given object implements the ApiRelationshipSchema interface.
 */
export declare function instanceOfApiRelationshipSchema(value: object): value is ApiRelationshipSchema;
export declare function ApiRelationshipSchemaFromJSON(json: any): ApiRelationshipSchema;
export declare function ApiRelationshipSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRelationshipSchema;
export declare function ApiRelationshipSchemaToJSON(json: any): ApiRelationshipSchema;
export declare function ApiRelationshipSchemaToJSONTyped(value?: ApiRelationshipSchema | null, ignoreDiscriminator?: boolean): any;
