"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * CrudSQL API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taqi@mobix.biz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfQueryQueryFilter = instanceOfQueryQueryFilter;
exports.QueryQueryFilterFromJSON = QueryQueryFilterFromJSON;
exports.QueryQueryFilterFromJSONTyped = QueryQueryFilterFromJSONTyped;
exports.QueryQueryFilterToJSON = QueryQueryFilterToJSON;
exports.QueryQueryFilterToJSONTyped = QueryQueryFilterToJSONTyped;
/**
 * Check if a given object implements the QueryQueryFilter interface.
 */
function instanceOfQueryQueryFilter(value) {
    return true;
}
function QueryQueryFilterFromJSON(json) {
    return QueryQueryFilterFromJSONTyped(json, false);
}
function QueryQueryFilterFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'expressions': json['expressions'] == null ? undefined : json['expressions'],
    };
}
function QueryQueryFilterToJSON(json) {
    return QueryQueryFilterToJSONTyped(json, false);
}
function QueryQueryFilterToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'expressions': value['expressions'],
    };
}
